name: Reveal Secret
on: workflow_dispatch # Allows you to run it manually

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal Secret
        env:
          SESSION: ${{ secrets.SESSION }} # Replace with your secret name
        run: |
          echo "$SESSION" | base64
